{{-  $serviceName := printf "%s-%s" .Values.name "headless-svc" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    job-name: {{ .Values.name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  completions: {{ .Values.replicaCount }}
  parallelism: {{ .Values.replicaCount }}
  completionMode: Indexed
  suspend: false
  backoffLimit: 0
  ttlSecondsAfterFinished: 1000
  template:
    metadata:
      labels:
        evaluation-id: {{ .Values.evaluationId }}
    spec:
      subdomain: {{ $serviceName }}
      restartPolicy: Never
{{- if .Values.multipleJobsPerNode }}
      hostNetwork: false
{{- else }}
      hostNetwork: true
{{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: data
          hostPath:
            path: /data/{{ .Values.datasetName }}
      nodeSelector:
        role: worker
      containers:
        - name: 'ddm-akka'
          image: {{ .Values.evaluationImage }}
          ports:
            - containerPort: 7877
              name: master-port
            - containerPort: 7879
              name: worker-port
            - containerPort: 7077
              name: spark-port
            - containerPort: 8091
              name: spark-stop
            - containerPort: 8080
              name: spark-ui-port
          volumeMounts:
            - name: data
              mountPath: /data/{{ .Values.datasetName }}
          env:
            - name: "JOB_NAME"
              value: {{ .Values.name }}
            - name: "EVALUATION_ID"
              value: {{ .Values.evaluationId }}
            - name: "SVC_NAME"
              value: {{ $serviceName }}
            - name: "NUMBER_OF_REPLICAS"
              value: {{ quote .Values.replicaCount }}
            - name: "GIT_URL"
              value: {{ .Values.gitUrl }}
{{- if .Values.gitBranch }}
            - name: "GIT_BRANCH"
              value: {{ .Values.gitBranch }}
{{- end }}
            - name: "OFFLINE_MODE"
              value: "false"
            - name: "ADDITIONAL_MAVEN_ARGS"
              value: "-DskipTests"
            - name: "RESULTS_ENDPOINT"
              value: "http://{{ .Values.evaluationEngineHost }}:{{ .Values.evaluationEnginePort }}/api/fileIngestion/results"
            - name: "LOGS_ENDPOINT"
              value: "http://{{ .Values.evaluationEngineHost }}:{{ .Values.evaluationEnginePort }}/api/fileIngestion/logs"
            - name: "EVENT_INGESTION_ENDPOINT"
              value: "http://{{ .Values.evaluationEngineHost }}:{{ .Values.evaluationEnginePort }}/ingest/event"
            - name: "EVALUATION_SERVICE_ALL_PODS_READY_TO_RUN_ENDPOINT"
              value: "http://{{ .Values.evaluationEngineHost }}:{{ .Values.evaluationEnginePort }}/api/evaluation/allPodsReadyToRun"
            - name: "LOG_ANALYZER_ENDPOINT"
              value: "http://localhost:8089/ingest/logfiles"
            - name: "APPLY_PATCH"
              value: "true"
            - name: "LOG_TO_CONSOLE"
              value: "true"
            #            - name: "REMOVE_LINES_IN_FILES"
            #              value: "./data/TPCH/tpch_lineitem.csv,./data/TPCH/tpch_orders.csv"
            #            - name: "REMOVE_AMOUNT_IN_PERCENT"
            #              value: "50"
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: "DATA_PATH"
              value: {{ .Values.datasetPath }}
            {{- range $key, $value := $.Values.startCommands }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            requests:
              #memory: "2048Mi"
              memory: {{ .Values.memoryRequest }}
              cpu: {{ .Values.cpuRequest }}
            limits:
              memory: {{ .Values.memoryLimit }}
              cpu: {{ .Values.cpuLimit }}
{{- if not .Values.multipleJobsPerNode }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "job-name"
                    operator: In
                    values:
                      - {{ .Values.name }}
              topologyKey: "kubernetes.io/hostname"
{{- end }}